###
GET http://localhost:1234/foods/

###
GET http://localhost:1234/foods/2


###
GET http://localhost:1234/foods?type=comida 


###
PATCH  http://localhost:1234/foods/1
Content-Type: application/json

{
  "calories": 150
}